import {
    CutlassText,
    HorizontalDivider,
    PanelBase,
    CutlassScrollView,
    VerticalDivider,
} from "../../components/index.slint";
import { AppStore } from "../../store/index.slint";
import { Toolbar } from "toolbar.slint";
import { TrackLane } from "track-lane.slint";
import { TrackHead } from "track-head.slint";
import { Ruler } from "ruler.slint";
import { ClipView } from "clip.slint";
import { TimelineState } from "state.slint";
import { Sequence } from "../../models/index.slint";
import { EditorStore } from "../../store/index.slint";



    component ForceHeadSpace inherits Rectangle {
    property <length> force-head-space: 50px;

    height: force-head-space;
    background: transparent;
}

export component TimelinePanel inherits PanelBase {
    private property <length> track-spacing: AppStore.theme.metrics.spacing.sm;
    property <Sequence> sequence: EditorStore.project.sequence;

    VerticalLayout {

        spacing: AppStore.theme.metrics.spacing.none;

        Toolbar {
            height: AppStore.theme.metrics.layout.toolbar-height;
        }

        Ruler { }

        HorizontalLayout {

            spacing: 60px;

            Flickable {
                viewport-y <=> TimelineState.scroll-y;
                height: 100%;
                width: 100px;

                VerticalLayout {

                    spacing: track-spacing;
                    vertical-stretch: 1;

                    ForceHeadSpace { }

                    for t in sequence.tracks: TrackHead { }
                }

                VerticalDivider {
                    x: parent.width - self.width;
                    width: AppStore.theme.metrics.stroke.thin;
                }
            }

            Flickable {
                viewport-width: 1000000px;
                viewport-y <=> TimelineState.scroll-y;
                viewport-x <=> TimelineState.scroll-x;

                Rectangle {
                    background: #6d5555;
                    vertical-stretch: 1;
                    horizontal-stretch: 1;
                    VerticalLayout {
                        align-items: LayoutAlignItems.end;
                        alignment: LayoutAlignment.end;

                        spacing: track-spacing;

                        vertical-stretch: 1;
                        horizontal-stretch: 1;

                        ForceHeadSpace { }

                        for t in sequence.tracks: TrackLane {
                            for c in t.clips: ClipView {
                                model: c;
                            }
                        }
                    }
                }
            }
        }
    }
}
