import { PanelBase, PanelHeader } from "../../components/index.slint";
import { AppStore } from "../../store/index.slint";
import { EditorStore } from "../../store/index.slint";
import { TimelineLib } from "../../lib/timeline-lib.slint";
import { RationalTime } from "../../models/index.slint";
import { AppState } from "../../state.slint";

export component PreviewPanel inherits PanelBase {
    private property <RationalTime> sequence-duration:
        TimelineLib.sequence-duration(EditorStore.project.sequence);

    VerticalLayout {
        PanelHeader {
            title: "Preview";
        }

        spacing: AppStore.theme.metrics.spacing.none;

        VerticalLayout {
            padding-left: AppStore.theme.metrics.spacing.md;
            padding-right: AppStore.theme.metrics.spacing.md;
            padding-bottom: AppStore.theme.metrics.spacing.md;

            spacing: AppStore.theme.metrics.spacing.xl;

            HorizontalLayout {
                Image {
                    source: @image-url("../../../assets/texture.png");
                    image-fit: ImageFit.contain;
                }
            }

            HorizontalLayout {
                spacing: AppStore.theme.metrics.spacing.sm;
                height: 30px;
                horizontal-stretch: 1;

                Rectangle {
                    width: 33%;
                    clip: true;

                    HorizontalLayout {

                        alignment: LayoutAlignment.start;
                        spacing: AppStore.theme.metrics.spacing.sm;

                        Text {
                            text: TimelineLib.format-timecode(
                                0,
                                EditorStore.project.sequence.fps.num,
                                EditorStore.project.sequence.fps.den,
                                EditorStore.project.sequence.drop-frame,
                            );

                            horizontal-alignment: TextHorizontalAlignment.center;
                            vertical-alignment: TextVerticalAlignment.center;
                        }

                        Text {
                            text: "/";
                            color: #484848;
                            font-size: 16px;
                            font-weight: 700;

                            horizontal-alignment: TextHorizontalAlignment.center;
                            vertical-alignment: TextVerticalAlignment.center;
                        }

                        Text {
                            text: TimelineLib.format-timecode(
                                root.sequence-duration.value,
                                root.sequence-duration.rate.num,
                                root.sequence-duration.rate.den,
                                EditorStore.project.sequence.drop-frame,
                            );

                            horizontal-alignment: TextHorizontalAlignment.center;
                            vertical-alignment: TextVerticalAlignment.center;
                        }
                    }
                }

                Rectangle {
                    width: 33%;

                    HorizontalLayout {
                        alignment: LayoutAlignment.center;

                        Image {
                            source: @image-url("../../assets/icon/play.svg");
                            image-fit: ImageFit.contain;
                            colorize: #ffffff;

                            horizontal-alignment: ImageHorizontalAlignment.center;
                            vertical-alignment: ImageVerticalAlignment.center;
                        }
                    }
                }

                Rectangle {
                    width: 33%;
                    HorizontalLayout {
                        alignment: LayoutAlignment.end;
                        Image {
                            source: @image-url("../../assets/icon/fullscreen.svg");
                            image-fit: ImageFit.contain;
                            colorize: #ffffff;

                            TouchArea {
                                clicked => {
                                    // AppState.enter-preview-maximized();
                                    AppState.preview-maximized = true;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
