
import { TimelineState } from "./state.slint";

export component PlayHead inherits Rectangle {
    in property <length> head-width: 12px;
    in property <length> head-height: 16px;
    in property <length> head-radius: 3px;
    in property <length> head-bottom-radius: 6px;
    in property <length> stroke-width: 1.5px;
    in property <length> line-width: 1.2px;
    in property <brush> playhead-color: #ffffff;
    in property <length> content-width: 1000000px;
    in-out property <length> line-pos: 0px;
    width: head-width;
    background: transparent;

    out property <length> line-x: (self.width - stroke-width) / 2;
    out property <length> clamp-min-x: 0px;
    out property <length> clamp-max-x: content-width - head-width + line-x;

    x: line-pos - line-x + TimelineState.scroll-x;

    head := Rectangle {
        y: 0;
        x: 0;
        width: head-width;
        height: head-height;
        border-top-left-radius: head-radius;
        border-top-right-radius: head-radius;
        border-bottom-left-radius: head-bottom-radius;
        border-bottom-right-radius: head-bottom-radius;
        background: transparent;
        border-width: stroke-width;
        border-color: root.playhead-color;
    }

    Rectangle {
        x: line-x;
        y: head-height;
        width: line-width;
        height: parent.height - head-height;
        background: root.playhead-color;
    }

}
