"""Type stubs for the cutlass native extension."""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any, Literal

import numpy as np
from numpy.typing import NDArray

__version__: str

TrackKind = Literal["video", "audio", "text", "sticker", "effect", "filter", "adjustment"]
CanvasAspect = Literal["auto", "16:9", "9:16", "1:1", "4:5", "21:9"]
Color = tuple[int, int, int] | tuple[int, int, int, int] | str
Easing = Literal["linear", "ease_in", "ease_out", "ease_in_out"] | tuple[float, float, float, float]
Keyframe = tuple[float, Any] | tuple[float, Any, Easing]
Content = (
    Media | MediaSlice | Text | Solid | Rect | Ellipse | Polygon | Star | Line | Arrow | Heart
)

class CutlassError(Exception): ...
class OverlapError(CutlassError): ...
class TrackKindError(CutlassError): ...
class MediaError(CutlassError): ...
class RenderError(CutlassError): ...

class Project:
    def __init__(
        self,
        name: str,
        fps: int = 30,
        canvas: CanvasAspect = "auto",
        background: Color | None = None,
    ) -> None: ...
    @staticmethod
    def load(path: str) -> Project: ...
    def save(self, path: str) -> None: ...
    def import_media(self, path: str) -> Media: ...
    def remove_media(self, media: Media) -> None: ...
    @property
    def media(self) -> list[Media]: ...
    def add_track(
        self,
        kind: TrackKind,
        name: str = "",
        index: int | None = None,
    ) -> Track: ...
    @property
    def tracks(self) -> list[Track]: ...
    def track(self, name: str) -> Track: ...
    @property
    def canvas(self) -> str: ...
    @canvas.setter
    def canvas(self, aspect: CanvasAspect) -> None: ...
    @property
    def background(self) -> tuple[int, int, int]: ...
    @background.setter
    def background(self, color: Color) -> None: ...
    def load_font(self, path: str) -> None: ...
    def get_frame(self, t: float) -> NDArray[np.uint8]: ...
    def export(self, path: str) -> int: ...
    @property
    def duration(self) -> float: ...
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def fps(self) -> float: ...

class Media:
    @property
    def path(self) -> str: ...
    @property
    def kind(self) -> Literal["video", "audio", "image"]: ...
    @property
    def duration(self) -> float: ...
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def fps(self) -> float: ...
    @property
    def has_audio(self) -> bool: ...
    def subclip(self, start: float, end: float | None = None) -> MediaSlice: ...
    def __getitem__(self, key: slice) -> MediaSlice: ...

class MediaSlice: ...

class Track:
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def main(self) -> bool: ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...
    @property
    def muted(self) -> bool: ...
    @muted.setter
    def muted(self, value: bool) -> None: ...
    @property
    def locked(self) -> bool: ...
    @locked.setter
    def locked(self, value: bool) -> None: ...
    def add(
        self,
        content: Content,
        start: float,
        duration: float | None = None,
    ) -> Clip: ...
    def append(self, content: Content, duration: float | None = None) -> Clip: ...
    @property
    def clips(self) -> list[Clip]: ...
    def clip_at(self, t: float) -> Clip | None: ...
    @property
    def end(self) -> float: ...
    def remove(self) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Clip]: ...

class Clip:
    @property
    def start(self) -> float: ...
    @property
    def end(self) -> float: ...
    @property
    def duration(self) -> float: ...
    @property
    def track(self) -> Track: ...
    @property
    def media(self) -> Media | None: ...
    @property
    def source_start(self) -> float | None: ...
    @property
    def source_duration(self) -> float | None: ...
    def split(self, at: float) -> Clip: ...
    def trim(self, start: float | None = None, end: float | None = None) -> None: ...
    def move(self, start: float, track: Track | None = None) -> None: ...
    def delete(self) -> None: ...
    def ripple_delete(self) -> None: ...
    @property
    def position(self) -> tuple[float, float]: ...
    @position.setter
    def position(self, value: tuple[float, float]) -> None: ...
    @property
    def anchor(self) -> tuple[float, float]: ...
    @anchor.setter
    def anchor(self, value: tuple[float, float]) -> None: ...
    @property
    def scale(self) -> float: ...
    @scale.setter
    def scale(self, value: float) -> None: ...
    @property
    def rotation(self) -> float: ...
    @rotation.setter
    def rotation(self, value: float) -> None: ...
    @property
    def opacity(self) -> float: ...
    @opacity.setter
    def opacity(self, value: float) -> None: ...
    @property
    def animation_in(self) -> str | None: ...
    @property
    def animation_out(self) -> str | None: ...
    @property
    def animation_combo(self) -> str | None: ...
    def set_animation(self, slot: str, animation_id: str | None = None) -> None: ...
    def transform_at(self, t: float) -> tuple[tuple[float, float], float, float, float]: ...
    def animate(self, **kwargs: Any) -> None: ...
    def remove_keyframe(self, name: str, *, at: float) -> None: ...
    def clear_animation(self, *names: str) -> None: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, value: float) -> None: ...
    @property
    def fade_in(self) -> float: ...
    @fade_in.setter
    def fade_in(self, value: float) -> None: ...
    @property
    def fade_out(self) -> float: ...
    @fade_out.setter
    def fade_out(self, value: float) -> None: ...
    def set_speed(self, factor: float, reverse: bool = False) -> None: ...
    @property
    def speed(self) -> float: ...
    @property
    def reversed(self) -> bool: ...
    def crop(
        self,
        x: float = 0.0,
        y: float = 0.0,
        w: float = 1.0,
        h: float = 1.0,
        flip_h: bool = False,
        flip_v: bool = False,
    ) -> None: ...
    def add_effect(self, effect_id: str, **params: float) -> Effect: ...
    @property
    def effects(self) -> list[Effect]: ...
    def remove_effect(self, effect: Effect) -> None: ...
    def transition(self, transition_id: str, duration: float | None = None) -> None: ...
    def remove_transition(self) -> None: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    def set_style(self, **kwargs: Any) -> None: ...

class Effect:
    def __getitem__(self, name: str) -> float: ...
    def __setitem__(self, name: str, value: float) -> None: ...
    def animate(self, **kwargs: Any) -> None: ...

class Text:
    def __init__(
        self,
        content: str,
        font: str = "",
        size: float = 90.0,
        color: Color | None = None,
        bold: bool = False,
        italic: bool = False,
        underline: bool = False,
        case: Literal["normal", "upper", "lower", "title"] = "normal",
        letter_spacing: float = 0.0,
        line_spacing: float = 1.2,
        align: tuple[str, str] = ("center", "middle"),
        wrap: bool = True,
        stroke: TextStroke | None = None,
        background: TextBackground | None = None,
        shadow: TextShadow | None = None,
    ) -> None: ...

class TextStroke:
    def __init__(self, color: Color, width: float = 6.0) -> None: ...

class TextBackground:
    def __init__(self, color: Color, radius: float = 0.0) -> None: ...

class TextShadow:
    def __init__(self, color: Color, blur: float = 0.15, distance: float = 5.0) -> None: ...

class Solid:
    def __init__(self, color: Color) -> None: ...

class Sticker:
    def __init__(self, asset: str) -> None: ...

class ShapeStroke:
    def __init__(self, color: Color, width: float = 8.0) -> None: ...

class Rect:
    def __init__(
        self,
        width: float = 200.0,
        height: float = 200.0,
        color: Color | None = None,
        corner_radius: float = 0.0,
        stroke: ShapeStroke | None = None,
    ) -> None: ...

class Ellipse:
    def __init__(
        self,
        width: float = 200.0,
        height: float = 200.0,
        color: Color | None = None,
        corner_radius: float = 0.0,
        stroke: ShapeStroke | None = None,
    ) -> None: ...

class Polygon:
    def __init__(
        self,
        sides: int,
        width: float = 200.0,
        height: float = 200.0,
        color: Color | None = None,
        corner_radius: float = 0.0,
        stroke: ShapeStroke | None = None,
    ) -> None: ...

class Star:
    def __init__(
        self,
        points: int,
        inner_ratio: float = 0.5,
        width: float = 200.0,
        height: float = 200.0,
        color: Color | None = None,
        stroke: ShapeStroke | None = None,
    ) -> None: ...

class Line:
    def __init__(
        self,
        length: float = 200.0,
        thickness: float = 8.0,
        color: Color | None = None,
        stroke: ShapeStroke | None = None,
    ) -> None: ...

class Arrow:
    def __init__(
        self,
        width: float = 200.0,
        height: float = 200.0,
        color: Color | None = None,
        corner_radius: float = 0.0,
        stroke: ShapeStroke | None = None,
    ) -> None: ...

class Heart:
    def __init__(
        self,
        width: float = 200.0,
        height: float = 200.0,
        color: Color | None = None,
        corner_radius: float = 0.0,
        stroke: ShapeStroke | None = None,
    ) -> None: ...

def effects() -> list[dict[str, Any]]: ...
def transitions() -> list[dict[str, Any]]: ...
def stickers() -> list[dict[str, Any]]: ...
def animations() -> list[dict[str, Any]]: ...
