export component PreviewPanel inherits Rectangle {
    horizontal-stretch: 1;
    vertical-stretch: 1;
    // background: #0c0c0e;

    in property <image> gpu-frame;

    Rectangle {
        vertical-stretch: 1;
        background: #121216;

        Image {
            width: 100%;
            height: 100%;
                // source: root.gpu-frame;
                source: @image-url("../../../renderer/assets/texture.png");
            image-fit: contain;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
