import { AppState } from "../models/app_state.slint";

export component PreviewPanel inherits Rectangle {
    horizontal-stretch: 1;
    vertical-stretch: 1;

    Rectangle {
        vertical-stretch: 1;
        background: #121216;

        Image {
            width: 100%;
            height: 100%;
            source: AppState.preview-frame;
            image-fit: contain;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
